FROM node:22-alpine
WORKDIR /app
RUN corepack enable
ENV HOST=0.0.0.0 PORT=3000
COPY app/package.json app/yarn.lock app/.yarnrc.yml ./
RUN yarn install --immutable
COPY app/ ./
EXPOSE 3000
CMD ["yarn", "dev"]
