# Generated by Django 5.2.17 on 2026-09-04 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='название')),
                ('description', models.TextField(blank=True, verbose_name='описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='catalog/', verbose_name='картинка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='изменен')),
            ],
            options={
                'verbose_name': 'элемент каталога',
                'verbose_name_plural': 'каталог',
                'ordering': ('-created_at',),
            },
        ),
    ]
