# Generated by Django 5.2.17 on 2026-09-21 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogitem',
            name='is_public',
            field=models.BooleanField(default=False, verbose_name='публичный'),
        ),
    ]
